global using System.Runtime.InteropServices;
global using static WinApiWrapper.GenericConstants.SystemErrorCodes;
global using static WinApiWrapper.GenericConstants.HRESULTErrorCodes;
global using static WinApiWrapper.Utilities;
global using static WinApiWrapper.Macros;
global using static WinApiWrapper.GenericConstants.OtherConstants;
global using BOOL = System.Boolean;
global using HWND = System.IntPtr;
global using LRESULT = System.IntPtr;
global using DWORD = System.UInt32;
global using LCID = System.UInt32;
global using LONG = System.Int32;
global using ULONG = System.UInt32;
global using WPARAM = System.IntPtr;
global using LPARAM = System.IntPtr;
global using HRGN = System.IntPtr;
global using HRESULT = System.Int32;
global using ULONGLONG = System.UInt64;
global using QPC_TIME = System.UInt64;
global using DWM_FRAME_COUNT = System.UInt64;
global using HTHUMBNAIL = System.IntPtr;
global using HBITMAP = System.IntPtr;
global using SHORT = System.Int16;
global using SIZE_T = System.IntPtr;
global using PVOID = System.IntPtr;
global using LPCWSTR = System.String;
global using LPWSTR = System.String;
global using LPTSTR = System.String;
global using WORD = System.UInt16;
global using DPI_AWARENESS_CONTEXT = System.IntPtr;
global using HMONITOR = System.IntPtr;
global using HANDLE = System.IntPtr;
global using HTHEME = System.IntPtr;
global using HINSTANCE = System.IntPtr;
global using HGDIOBJ = System.IntPtr;
global using ATOM = System.UInt16;
global using LONG_PTR = System.IntPtr;
global using PCWSTR = System.String;
global using CALID = System.UInt32;
global using CALTYPE = System.UInt32;
global using WCHAR = System.Char;
global using LCTYPE = System.UInt32;
global using LPCWCH = System.String;
global using DWORD_PTR = System.IntPtr;
global using HIMAGELIST = System.IntPtr;
global using HDC = System.IntPtr;
global using COLORREF = System.UInt32;
global using HICON = System.IntPtr;
global using HBRUSH = System.IntPtr;
global using HPEN = System.IntPtr;
global using HTREEITEM = System.IntPtr;
global using ULONG_PTR = System.IntPtr;
global using LANGID = System.UInt16;
global using HMODULE = System.IntPtr;
global using UINT_PTR = System.UIntPtr;
global using HGLOBAL = System.IntPtr;